title: QoolDB
description: "5 4 3 2 1 Collections of stuff from the internet."
author:
  name: "QoolDB"
  email: "norcads@gmail.com"
  url: "/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "QoolDB"
year : "2020"
